all:
	$(CC) $(CFLAGS) -Wall -c  mapped_file.c -o "$(MAKED)/mapped_file.o"
	$(CC) $(CFLAGS) -Wall -c  hash_table/hash_table.c -o "$(MAKED)/hash_table.o"

test:

clean:
	rm -f "$(MAKED)/test-log" "$(MAKED)/"*.o
